import api from './client'

export const getK8sRollouts = (serverId) => api.get('/k8s/rollouts', { params: { server_id: serverId } })
export const k8sOnlinePreview = (data) => api.post('/k8s/online/preview', data)
export const k8sOnlineExecute = (data) => api.post('/k8s/online/execute', data, { timeout: 600000 })
export const k8sSyncPreview = (data) => api.post('/k8s/sync/preview', data)
export const k8sSyncExecute = (data) => api.post('/k8s/sync/execute', data, { timeout: 600000 })
export const k8sRollbackPreview = (data) => api.post('/k8s/rollback/preview', data)
export const k8sRollbackExecute = (data) => api.post('/k8s/rollback/execute', data, { timeout: 600000 })
export const k8sFullOnlinePreview = (data) => api.post('/k8s/full_online/preview', data)
export const k8sFullOnlineExecute = (data) => api.post('/k8s/full_online/execute', data, { timeout: 600000 })
export const k8sFullSyncPreview = (data) => api.post('/k8s/full_sync/preview', data)
export const k8sFullSyncExecute = (data) => api.post('/k8s/full_sync/execute', data, { timeout: 600000 })
export const k8sFullRollbackPreview = (data) => api.post('/k8s/full_rollback/preview', data)
export const k8sFullRollbackExecute = (data) => api.post('/k8s/full_rollback/execute', data, { timeout: 600000 })
