import api from './client'

export const getLvsList = (serverId) => api.get('/lvs/list', { params: { server_id: serverId } })
export const getLvsStatus = (serverId) => api.get('/lvs/status', { params: { server_id: serverId } })
export const lvsOpPreview = (data) => api.post('/lvs/op/preview', data)
export const lvsOpExecute = (data) => api.post('/lvs/op/execute', data)
export const lvsSwapPreview = (data) => api.post('/lvs/swap/preview', data)
export const lvsSwapExecute = (data) => api.post('/lvs/swap/execute', data)
export const getLvsTags = (params) => api.get('/lvs/tags', { params })
export const updateLvsTag = (data) => api.put('/lvs/tags', data)
export const deleteLvsTag = (vsIp, rsIp) =>
  api.delete(`/lvs/tags/${encodeURIComponent(vsIp)}/${encodeURIComponent(rsIp)}`)
export const getLvsVSTags = (params) => api.get('/lvs/vs_tags', { params })
export const updateLvsVSTag = (data) => api.put('/lvs/vs_tags', data)
export const deleteLvsVSTag = (vsIp) => api.delete(`/lvs/vs_tags/${encodeURIComponent(vsIp)}`)
export const getLvsBindings = (params) => api.get('/lvs/bindings', { params })
export const updateLvsBinding = (data) => api.put('/lvs/bindings', data)
export const deleteLvsBinding = (id) => api.delete(`/lvs/bindings/${id}`)
export const checkLvsForScaleDown = (data) => api.post('/lvs/check/scaledown', data)
export const checkLvsOnlineForPreprod = (data) => api.post('/preprod/check/lvs_online', data)
